name: パックを指定したバージョンに更新

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '新バージョン'
        required: true
        default: 'b0.0.0' # AUTO-UPDATE

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: トークンを生成
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ vars.APP_ID }}
        private-key: ${{ secrets.PRIVATE_KEY }}
    
    - name: GitHub App User IDを取得
      id: get-user-id
      env:
        GH_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: echo "user-id=$(gh api "/users/${{ steps.generate-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
    
    - name: Commiterを設定
      run: |
        git config --global user.name '${{ steps.generate-token.outputs.app-slug }}[bot]'
        git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.generate-token.outputs.app-slug }}[bot]@users.noreply.github.com'
        git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
    
    - name: リポジトリをチェックアウト
      uses: actions/checkout@v4
    
    - name: バージョンを書き換え
      run: |
        tag=${{ github.event.inputs.tag }}
        echo "tag=${tag}"
        sed -i "s/PACK_VERSION=".*"/PACK_VERSION=\"${tag}\"/" gen-pack-config.sh
        sed -i "s/( +default: )'.*" # AUTO-UPDATE/\1'${tag}'/" .github/workflows/gen-release.yml
      shell: bash
    
    - name: コミットしタグ付きでプッシュ
      env:
        GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}
      run: |
        git config --global push.followTags true
        git add gen-pack-config.sh
        git commit -m 'パックバージョンを${{ github.event.inputs.tag }}に更新'
        git tag -a ${{ github.event.inputs.tag }} -m 'パックバージョン${{ github.event.inputs.tag }}'
        git push
    
    - name: パックを生成
      id: gen-pack
      run: |
        echo "pack_file_name=$(./gen-pack.sh)" | tee -a $GITHUB_OUTPUT
      shell: bash
    
    - name: パックを解凍
      run: |
        cd pack
        unzip ${{ steps.gen-pack.outputs.pack_file_name }}.zip -d ${{ steps.gen-pack.outputs.pack_file_name }}
      shell: bash

    - name: Artifactsにアップロード
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.gen-pack.outputs.pack_file_name }}
        path: pack/${{ steps.gen-pack.outputs.pack_file_name }}/
    
    - name: リリースを作成
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/') # タグがpushされたときのみに限定
      with:
        generate_release_notes: true
        files: pack/*.zip
